# Generated by Django 3.1.7 on 2021-06-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=200)),
                ('institution_email', models.CharField(max_length=200)),
                ('graduation_year', models.CharField(max_length=100)),
            ],
        ),
    ]
