# Generated by Django 3.1.7 on 2021-06-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_registers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
