# Generated by Django 3.2.3 on 2021-06-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
