# Generated by Django 3.1.7 on 2021-07-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='registers',
            name='profile_image',
            field=models.ImageField(default='', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='upload',
            name='profile_image',
            field=models.ImageField(default='', upload_to='pics'),
        ),
    ]
