# Generated by Django 3.2.5 on 2021-07-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210706_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnVerified',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=200)),
                ('institution_email', models.CharField(max_length=200)),
                ('graduation_year', models.CharField(max_length=100)),
            ],
        ),
    ]
