# Generated by Django 3.2.5 on 2021-08-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_registers_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='profile_image',
            field=models.ImageField(default='', upload_to='pics'),
        ),
    ]
