# Generated by Django 3.2.5 on 2021-09-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_signup_yourdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('institution_email', models.CharField(max_length=200)),
                ('graduation_year', models.CharField(max_length=100)),
            ],
        ),
    ]
