# Generated by Django 3.2.5 on 2021-09-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_institution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
