# Generated by Django 3.2.7 on 2021-09-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_delete_institution'),
        ('account', '0012_unverified_verification_url'),
    ]

    operations = [
    ]
