# Generated by Django 3.2.7 on 2022-03-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=500)),
                ('desc', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('logo', models.ImageField(upload_to='brands')),
            ],
        ),
    ]
