# Generated by Django 3.2.3 on 2021-06-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='users/%Y/%m/')),
                ('brandlogo', models.ImageField(default='', upload_to='users/%Y/%m/')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
