# Generated by Django 3.2.3 on 2021-06-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_brand_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
