# Generated by Django 3.2.3 on 2021-06-20 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
