# Generated by Django 3.2.3 on 2021-06-20 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='users/%Y/%m/')),
                ('brandlogo', models.ImageField(default='', upload_to='users/%Y/%m/')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=1000)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
