# Generated by Django 3.2.3 on 2021-06-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210624_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brandlogo',
            field=models.ImageField(default='', upload_to='tiles'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='', upload_to='tiles'),
        ),
    ]
