# Generated by Django 3.2.5 on 2021-08-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210718_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foundation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('coursename', models.CharField(default='', max_length=100)),
                ('courselink', models.CharField(max_length=500)),
                ('desc', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
