# Generated by Django 3.2.5 on 2021-09-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_resource_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='college',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default=1, max_length=3),
        ),
    ]
