# Generated by Django 3.2.5 on 2022-01-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundation',
            name='collegename',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='foundation',
            name='linkedinurl',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
